Blog app - creating a data model
HENRYKC24/Blog_App pull request #3
Opened 2022-01-15 06:12 UTC by HENRYKC24

## The following are done in this pull request:
- Build my project schema.
- Created and ran the necessary migration files.
- Table and column names match the ERD diagram.
- Photo for users table is a link to an image
- Foreign keys are included.
- All columns that are foreign keys have a corresponding index.

2022-01-15 06:52 UTC, Emmyn5600 requested changes
Hi @HENRYKC24 

Great work on making the project requirements 👏 
You've done well implementing some of the project requirements, but there are still some which aren't addressed yet, please work on it and ask for another review.

 ## Required Changes ♻️

- _Check the comment under the review._

## Optional suggestions

- Use this [link](https://guides.rubyonrails.org/getting_started.html) for more information about creating model data for your application.

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

#### _**Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise.**_
------------------------------------------------------------------------------------------------------------------------------
As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using this [form.](https://airtable.com/shrQAqnBwek5a0O0s)

2022-01-15 06:52 UTC, Emmyn5600 commented on db/migrate/20220115053923_create_posts.rb
> +end
- [ ] The `likes_counter` has to be t.integer instead of t.string
- [ ] You are missing the ` t.integer :comments_counter`

2022-01-15 06:52 UTC, Emmyn5600 commented on db/migrate/20220115054411_create_comments.rb
> +end
- [ ] `t.text :text` is missing in the comments table.

2022-01-18 14:04 UTC, closed without merging

2022-01-18 14:05 UTC, HENRYKC24 commented
This request has been linked with another.